import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const MulishFont = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Understanding money's building blocks",
  description: "Generated by Stanford Web Services",
  other: {
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MulishFont.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
