import type { Metadata } from "next";
import { Open_Sans as OpenSansFont } from "next/font/google";
import "./globals.css";

const openSans = OpenSansFont({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Understanding money's building blocks",
  description: "Generated by create next app",
  other: {
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
